### ISSUE TITLE
`reth-primitives` patched crates incompatible with `sp1-sdk`

### ISSUE THREAD

**Issue by plafer** [succinctlabs/sp1#525]
Currently, the following `Cargo.toml` fails to build

```toml
[workspace]
[package]
version = "0.1.0"
name = "my-package"
edition = "2021"

[dependencies]
reth-primitives = { git = "https://github.com/sp1-patches/reth", default-features = false, branch = "sp1-reth" }
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git" }
```

with error

```md
error: failed to select a version for c-kzg.
    ... required by package revm-primitives v2.0.0 (https://github.com/sp1-patches/revm.git?branch=patch-v5.0.0#c993e0d6)
    ... which satisfies git dependency revm-primitives of package reth-primitives v0.1.0-alpha.18 (https://github.com/sp1-patches/reth?branch=sp1-reth#3b31e8b3)
    ... which satisfies git dependency reth-primitives of package invariant-proof-script v0.1.0 (/Users/plaferriere/code/invariant-proof/script)
versions that meet the requirements ^0.4.1 are: 0.4.2, 0.4.1
the package c-kzg links to the native library ckzg, but it conflicts with a previous package which links to ckzg as well:
package c-kzg v1.0.0
    ... which satisfies dependency c-kzg = "^1.0" of package alloy-eips v0.1.0 (https://github.com/alloy-rs/alloy?rev=bfd0fda#bfd0fda4)
    ... which satisfies git dependency alloy-eips of package alloy v0.1.0 (https://github.com/alloy-rs/alloy?rev=bfd0fda#bfd0fda4)
    ... which satisfies git dependency alloy of package sp1-sdk v0.1.0 (https://github.com/succinctlabs/sp1.git#12c841b2)
    ... which satisfies git dependency sp1-sdk of package invariant-proof-script v0.1.0 (/Users/plaferriere/code/invariant-proof/script)
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links = "ckzg" value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.
failed to select a version for c-kzg which could resolve this conflict
```
